// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-000/Week04/work/models"
)

import (
	_ "Go-000/Week04/work/routers"
)

// Injectors from wire.go:

func InitializeEvent(msg string) models.Event {
	message := models.NewMessage(msg)
	greeter := models.NewGreeter(message)
	event := models.NewEvent(greeter)
	return event
}
